spring:
  datasource:
    username: C##vlad
    password: tiger
    url: "jdbc:oracle:thin:@localhost:1521:orcl"
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update